### ISSUE TITLE
Sbix export issues

### ISSUE THREAD

**Issue by djrrb** [fontfont/RoboChrome#6]
Finally getting around to playing with this awesome tool. I think I am able to generate SVG and COLR versions fine, but am encountering errors when exporting SBIX and I'm not sure how to proceed.

First, I think flatPen.py is missing an import for TransformPen (from fontTools.pens.transformPen import TransformPen). Happy to submit a pull request once I figure out what I'm doing.

After adding that import, I am now hitting a KeyError for either color palette that doesn't exit (I only have one), or a color (I have 4). Attached is a screenshot of how things look when I hit the error.

<img width="500" alt="screen shot 2015-09-27 at 12 14 40 am" src="https://cloud.githubusercontent.com/assets/6578861/10121179/7325dcc8-64ad-11e5-9c2d-c54d8a5df851.png">

The full error is below.

I acknowledge this is likely operator error. Do you have any idea what might be causing this? Thanks!

_export_to_font /Users/david/Desktop/Bungee_Color-Regular.ttf
Exporting to /Users/david/Desktop/Bungee_Color-Regular.ttf
Exporting sbix format ...
Traceback (most recent call last):
  File "/Applications/FontApps/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/dialogs.py", line 110, in savePanelDidEnd_returnCode_contextInfo_
    self._resultCallback(self._result)
  File "RoboChrome.py", line 163, in _export_to_font
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 325, in export_to_otf
    self._export_sbix(otfpath, palette_index, "png", replace_outlines, parent_window)
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 533, in _export_sbix
    image_data = self[glyphname].get_png(palette, current_ppem)
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 848, in get_png
    self.rasterize(palette_index, [size])
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 772, in rasterize
    _page = self._get_drawing(palette_index)
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 794, in _get_drawing
    layer_color = self.font._get_fcolor(palette_index, colorindex)
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 259, in _get_fcolor
    _hexrgba = self.palettes[palette_index][str(color_index)]
KeyError: '2'
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 169, in sendEvent_
  File "/Applications/FontApps/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/dialogs.py", line 110, in savePanelDidEnd_returnCode_contextInfo_
    self._resultCallback(self._result)
  File "RoboChrome.py", line 163, in _export_to_font
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 325, in export_to_otf
    self._export_sbix(otfpath, palette_index, "png", replace_outlines, parent_window)
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 533, in _export_sbix
    image_data = self[glyphname].get_png(palette, current_ppem)
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 848, in get_png
    self.rasterize(palette_index, [size])
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 772, in rasterize
    _page = self._get_drawing(palette_index)
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 794, in _get_drawing
    layer_color = self.font._get_fcolor(palette_index, colorindex)
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 259, in _get_fcolor
    _hexrgba = self.palettes[palette_index][str(color_index)]
KeyError: '2'

**Comment by jenskutilek** [comment]
I have committed an update which adds some error messages to this part of the code (and includes the TransformPen import, thanks for spotting this). Could you try again with the updated extension? And before exporting, when you hit the "Debug" button, there should be some information in the output panel, like this:

````
<ColorFont>
    Save settings: True
    Auto layer regex: \.layer[0-9]{2}$
    Auto layer includes base glyph: 0
    Bitmap sizes: [128, 256]
    Palettes:
        {'1': '#fff1f7ff', '0': '#410000ff', '3': '#000000ff', '2': '#910001ff'}
    Glyphs: ['box', 'circle']
        <ColorGlyph>
    Base glyph: box
    Layers: ['box.layer00', 'box.layer01']
    Colors: [0, 2]
    SVG:    
</ColorGlyph>

        <ColorGlyph>
    Base glyph: circle
    Layers: ['circle.layer00', 'circle.layer01', 'circle.layer02', 'circle.layer03']
    Colors: [0, 1, 2, 3]
    SVG:    
</ColorGlyph>

</ColorFont>
````

Perhaps the mismatching key can be spotted in this debug dump ...

**Comment by jenskutilek** [comment]
The key error shows a string, so there may be a mix-up between integer keys and string keys somewhere. The Vanilla table cells store strings even if the contents is a number, so some conversion is necessary in different places. Maybe there is something wrong with that somewhere.

BTW which RoboFont version are you using?

**Comment by djrrb** [comment]
Sorry for the delay ( doing this on weekends ;-) ), and thanks so much for your suggestions!

Attached is the full debug export (the palettes seem fine, don't they?), and below is the traceback using the latest version of Robochrome.

This is using robofont Version 1.7b (built 1507282329). 

If this gives you any ideas, great! I'm happy to try it on a different version of RF if you think it would make a difference. Thanks again!

_export_to_font /Users/david/Desktop/Bungee_Color-Regular.ttf
Exporting to /Users/david/Desktop/Bungee_Color-Regular.ttf
Exporting sbix format ...
ERROR: _get_fcolor(self, palette_index, color_index)
       Requested palette key 0 (<type 'int'>) not in available palette keys.
Traceback (most recent call last):
  File "/Applications/FontApps/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/dialogs.py", line 110, in savePanelDidEnd_returnCode_contextInfo_
    self._resultCallback(self._result)
  File "RoboChrome.py", line 163, in _export_to_font
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 337, in export_to_otf
    self._export_sbix(otfpath, palette_index, "png", replace_outlines, parent_window)
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 545, in _export_sbix
    image_data = self[glyphname].get_png(palette, current_ppem)
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 865, in get_png
    self.rasterize(palette_index, [size])
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 784, in rasterize
    _page = self._get_drawing(palette_index)
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 811, in _get_drawing
    layer_color = self.font._get_fcolor(palette_index, colorindex)
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 263, in _get_fcolor
    raise KeyError(palette_index)
KeyError: 0
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 169, in sendEvent_
  File "/Applications/FontApps/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/dialogs.py", line 110, in savePanelDidEnd_returnCode_contextInfo_
    self._resultCallback(self._result)
  File "RoboChrome.py", line 163, in _export_to_font
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 337, in export_to_otf
    self._export_sbix(otfpath, palette_index, "png", replace_outlines, parent_window)
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 545, in _export_sbix
    image_data = self[glyphname].get_png(palette, current_ppem)
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 865, in get_png
    self.rasterize(palette_index, [size])
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 784, in rasterize
    _page = self._get_drawing(palette_index)
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 811, in _get_drawing
    layer_color = self.font._get_fcolor(palette_index, colorindex)
  File "/Users/david/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 263, in _get_fcolor
    raise KeyError(palette_index)
KeyError: 0

**Comment by jenskutilek** [comment]
Sorry for the long delay, now I found some time to look into this again.

Actually I noticed that I introduced the above KeyError in the previous attempt to fix your error :/

A couple of things changed between RF 1.6 and 1.7, and now thanks to Frederik I have access to the betas. I fixed what I found to make everything work in 1.7.

That said, these fixes probably don't fix your problem. Could you try the new version though, and if it still doesn't export the font, maybe you could send me your UFO? Will send you a private e-mail.

Cheers!

**Comment by jenskutilek** [comment]
@djrrb I see you closed the issue in your repository. Is this something that still needs to be fixed in RoboChrome? Sorry, I kinda lost track on this a bit.

**Comment by djrrb** [comment]
Sorry I meant to follow up with you about this. I'm not sure if it was upgrading to El Capitan, upgrading to RoboFont 1.7b, or something else, but all of a sudden SBIX generation started working for me, even for large files. Sorry for all the trouble, and thanks so much for your help!
